CREATE TABLE IF NOT EXISTS Settings(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (username) REFERENCES Banana_data(username) ON DELETE CASCADE,
    darkMode BOOLEAN DEFAULT FALSE
);